package com.ferrisys.service.catalog.impl;

import com.ferrisys.common.dto.PageResponse;
import com.ferrisys.common.dto.catalog.CatalogDtos.*;
import com.ferrisys.common.entity.catalog.*;
import com.ferrisys.common.exception.impl.BadRequestException;
import com.ferrisys.common.exception.impl.ConflictException;
import com.ferrisys.common.exception.impl.NotFoundException;
import com.ferrisys.config.security.JWTUtil;
import com.ferrisys.core.tenant.TenantContextHolder;
import com.ferrisys.repository.TaxRepository;
import com.ferrisys.repository.catalog.*;
import com.ferrisys.service.catalog.CatalogService;
import java.time.OffsetDateTime;
import java.util.*;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service @RequiredArgsConstructor
public class CatalogServiceImpl implements CatalogService {
 private final TenantContextHolder tenant; private final JWTUtil jwt; private final TaxRepository taxRepository;
 private final MstCategoryRepository catRepo; private final MstBrandRepository brandRepo; private final MstUomGroupRepository uomGroupRepo; private final MstUomRepository uomRepo;
 private final MstUomConversionRepository convRepo; private final MstAttributeRepository attrRepo; private final MstAttributeOptionRepository attrOptRepo;
 private final MstTaxProfileRepository taxProfileRepo; private final MstTaxProfileTaxRepository taxProfileTaxRepo;

 private int p(int page){return Math.max(page-1,0);} private String s(String search){return search==null?"":search.trim();}
 private <T> PageResponse<T> page(Page<T> p, int req){return new PageResponse<>(p.getContent(),p.getTotalPages(),p.getTotalElements(),req,p.getSize());}
 private void softDelete(Object e){
   OffsetDateTime now=OffsetDateTime.now(); String u=jwt.getCurrentUser();
   if(e instanceof MstCategory x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} if(e instanceof MstBrand x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} if(e instanceof MstUomGroup x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} if(e instanceof MstUom x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} if(e instanceof MstUomConversion x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} if(e instanceof MstAttribute x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} if(e instanceof MstAttributeOption x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} if(e instanceof MstTaxProfile x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} if(e instanceof MstTaxProfileTax x){x.setActive(false);x.setDeletedAt(now);x.setDeletedBy(u);} }

 @Override public PageResponse<CategoryDto> listCategories(int page,int size,String search,Boolean active){UUID t=tenant.requireTenantId(); var p=catRepo.findByTenantIdAndDeletedAtIsNullAndNameContainingIgnoreCaseAndActive(t,s(search),active==null?true:active,PageRequest.of(p(page),size)); return page(p.map(this::toCategory),page);} 
 @Override public CategoryDto getCategory(UUID id){UUID t=tenant.requireTenantId(); return toCategory(catRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Categoría no encontrada")));}
 @Override @Transactional public CategoryDto saveCategory(CategoryDto dto){UUID t=tenant.requireTenantId(); if(Boolean.TRUE.equals(catRepo.existsByTenantIdAndNameIgnoreCaseAndDeletedAtIsNullAndActiveTrue(t,dto.name()))) throw new ConflictException("Nombre de categoría ya existe"); validateParent(t,dto.parentId()); MstCategory e=new MstCategory(); apply(e,dto,t); return toCategory(catRepo.save(e));}
 @Override @Transactional public CategoryDto updateCategory(UUID id,CategoryDto dto){UUID t=tenant.requireTenantId(); MstCategory e=catRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Categoría no encontrada")); if(Boolean.TRUE.equals(catRepo.existsByTenantIdAndNameIgnoreCaseAndDeletedAtIsNullAndActiveTrueAndIdNot(t,dto.name(),id))) throw new ConflictException("Nombre de categoría ya existe"); validateParent(t,dto.parentId()); apply(e,dto,t); return toCategory(catRepo.save(e));}
 @Override @Transactional public void deleteCategory(UUID id){UUID t=tenant.requireTenantId(); MstCategory e=catRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Categoría no encontrada")); softDelete(e); catRepo.save(e);} 
 @Override public List<CategoryTreeDto> treeCategories(){UUID t=tenant.requireTenantId(); List<MstCategory> all=catRepo.findByTenantIdAndDeletedAtIsNullAndActiveTrueOrderBySortOrderAscNameAsc(t); Map<UUID,List<MstCategory>> byParent=new HashMap<>(); for(var c:all) byParent.computeIfAbsent(c.getParentId(),k->new ArrayList<>()).add(c); return buildTree(null,byParent);} 
 private List<CategoryTreeDto> buildTree(UUID p,Map<UUID,List<MstCategory>> byParent){return byParent.getOrDefault(p,List.of()).stream().map(c->new CategoryTreeDto(c.getId(),c.getName(),buildTree(c.getId(),byParent))).toList();}
 private void validateParent(UUID t, UUID parentId){ if(parentId==null)return; catRepo.findByIdAndTenantIdAndDeletedAtIsNull(parentId,t).orElseThrow(()->new BadRequestException("Categoría padre inválida"));}
 private void apply(MstCategory e, CategoryDto d, UUID t){e.setTenantId(t); e.setCode(d.code()); e.setName(d.name()); e.setParentId(d.parentId()); e.setSortOrder(d.sortOrder()==null?0:d.sortOrder()); if(d.active()!=null)e.setActive(d.active()); e.setDeletedAt(null); e.setDeletedBy(null);} private CategoryDto toCategory(MstCategory e){return new CategoryDto(e.getId(),e.getCode(),e.getName(),e.getParentId(),e.getSortOrder(),e.getActive());}

 @Override public PageResponse<BrandDto> listBrands(int page,int size,String search,Boolean active){UUID t=tenant.requireTenantId(); var p=brandRepo.findByTenantIdAndDeletedAtIsNullAndNameContainingIgnoreCaseAndActive(t,s(search),active==null?true:active,PageRequest.of(p(page),size)); return page(p.map(x->new BrandDto(x.getId(),x.getCode(),x.getName(),x.getActive())),page);} 
 @Override public BrandDto getBrand(UUID id){UUID t=tenant.requireTenantId(); var b=brandRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Marca no encontrada")); return new BrandDto(b.getId(),b.getCode(),b.getName(),b.getActive());}
 @Override @Transactional public BrandDto saveBrand(BrandDto dto){UUID t=tenant.requireTenantId(); if(brandRepo.existsByTenantIdAndNameIgnoreCaseAndDeletedAtIsNullAndActiveTrue(t,dto.name())) throw new ConflictException("Marca ya existe"); MstBrand e=new MstBrand(); e.setTenantId(t); e.setCode(dto.code()); e.setName(dto.name()); e.setActive(dto.active()==null?true:dto.active()); return getBrand(brandRepo.save(e).getId());}
 @Override @Transactional public BrandDto updateBrand(UUID id,BrandDto dto){UUID t=tenant.requireTenantId(); if(brandRepo.existsByTenantIdAndNameIgnoreCaseAndDeletedAtIsNullAndActiveTrueAndIdNot(t,dto.name(),id)) throw new ConflictException("Marca ya existe"); MstBrand e=brandRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Marca no encontrada")); e.setCode(dto.code());e.setName(dto.name()); if(dto.active()!=null)e.setActive(dto.active()); return getBrand(brandRepo.save(e).getId());}
 @Override @Transactional public void deleteBrand(UUID id){UUID t=tenant.requireTenantId(); var e=brandRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Marca no encontrada")); softDelete(e); brandRepo.save(e);} 

 @Override public PageResponse<UomGroupDto> listUomGroups(int page,int size,String search,Boolean active){UUID t=tenant.requireTenantId(); var p=uomGroupRepo.findByTenantIdAndDeletedAtIsNullAndNameContainingIgnoreCaseAndActive(t,s(search),active==null?true:active,PageRequest.of(p(page),size)); return page(p.map(x->new UomGroupDto(x.getId(),x.getName(),x.getActive())),page);} 
 @Override public UomGroupDto getUomGroup(UUID id){UUID t=tenant.requireTenantId(); var e=uomGroupRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Grupo UOM no encontrado")); return new UomGroupDto(e.getId(),e.getName(),e.getActive());}
 @Override @Transactional public UomGroupDto saveUomGroup(UomGroupDto dto){UUID t=tenant.requireTenantId(); MstUomGroup e=new MstUomGroup(); e.setTenantId(t); e.setName(dto.name()); e.setActive(dto.active()==null?true:dto.active()); return getUomGroup(uomGroupRepo.save(e).getId());}
 @Override @Transactional public UomGroupDto updateUomGroup(UUID id,UomGroupDto dto){UUID t=tenant.requireTenantId(); var e=uomGroupRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Grupo UOM no encontrado")); e.setName(dto.name()); if(dto.active()!=null)e.setActive(dto.active()); return getUomGroup(uomGroupRepo.save(e).getId());}
 @Override @Transactional public void deleteUomGroup(UUID id){UUID t=tenant.requireTenantId(); var e=uomGroupRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Grupo UOM no encontrado")); softDelete(e); uomGroupRepo.save(e);} 

 @Override public PageResponse<UomDto> listUoms(int page,int size,String search,Boolean active,UUID groupId){UUID t=tenant.requireTenantId(); Page<MstUom> p=groupId==null?uomRepo.findByTenantIdAndDeletedAtIsNullAndNameContainingIgnoreCaseAndActive(t,s(search),active==null?true:active,PageRequest.of(this.p(page),size)):uomRepo.findByTenantIdAndDeletedAtIsNullAndGroupId(t,groupId,PageRequest.of(this.p(page),size)); return page(p.map(this::toUom),page);} private UomDto toUom(MstUom e){return new UomDto(e.getId(),e.getGroupId(),e.getName(),e.getSymbol(),e.getIsBase(),e.getActive());}
 @Override public UomDto getUom(UUID id){UUID t=tenant.requireTenantId(); return toUom(uomRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("UOM no encontrado")));}
 @Override @Transactional public UomDto saveUom(UomDto dto){UUID t=tenant.requireTenantId(); validateGroup(t,dto.groupId()); MstUom e=new MstUom(); e.setTenantId(t); e.setGroupId(dto.groupId()); e.setName(dto.name()); e.setSymbol(dto.symbol()); e.setIsBase(dto.isBase()!=null&&dto.isBase()); e.setActive(dto.active()==null?true:dto.active()); ensureGroupHasBase(t,dto.groupId(),e); return getUom(uomRepo.save(e).getId());}
 @Override @Transactional public UomDto updateUom(UUID id,UomDto dto){UUID t=tenant.requireTenantId(); MstUom e=uomRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("UOM no encontrado")); validateGroup(t,dto.groupId()); e.setGroupId(dto.groupId()); e.setName(dto.name()); e.setSymbol(dto.symbol()); if(dto.isBase()!=null)e.setIsBase(dto.isBase()); if(dto.active()!=null)e.setActive(dto.active()); ensureGroupHasBase(t,dto.groupId(),e); return getUom(uomRepo.save(e).getId());}
 @Override @Transactional public void deleteUom(UUID id){UUID t=tenant.requireTenantId(); var e=uomRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("UOM no encontrado")); softDelete(e); uomRepo.save(e);} 
 private void validateGroup(UUID t, UUID g){uomGroupRepo.findByIdAndTenantIdAndDeletedAtIsNull(g,t).orElseThrow(()->new BadRequestException("Grupo UOM inválido"));}
 private void ensureGroupHasBase(UUID t, UUID groupId, MstUom current){List<MstUom> list=uomRepo.findByTenantIdAndGroupIdAndDeletedAtIsNullAndActiveTrue(t,groupId); boolean anyBase=list.stream().anyMatch(MstUom::getIsBase)||Boolean.TRUE.equals(current.getIsBase()); if(!anyBase) throw new BadRequestException("Debe existir una UOM base por grupo");}

 @Override public PageResponse<UomConversionDto> listUomConversions(int page,int size,UUID groupId){UUID t=tenant.requireTenantId(); var p=convRepo.findByTenantIdAndDeletedAtIsNullAndGroupId(t,groupId,PageRequest.of(this.p(page),size)); return page(p.map(this::toConv),page);} private UomConversionDto toConv(MstUomConversion e){return new UomConversionDto(e.getId(),e.getGroupId(),e.getFromUomId(),e.getToUomId(),e.getFactor(),e.getActive());}
 @Override public UomConversionDto getUomConversion(UUID id){UUID t=tenant.requireTenantId(); return toConv(convRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Conversión no encontrada")));}
 @Override @Transactional public UomConversionDto saveUomConversion(UomConversionDto dto){UUID t=tenant.requireTenantId(); if(dto.factor()==null||dto.factor().signum()<=0) throw new BadRequestException("Factor inválido"); validateUomTenant(t,dto.groupId(),dto.fromUomId()); validateUomTenant(t,dto.groupId(),dto.toUomId()); MstUomConversion e=new MstUomConversion(); e.setTenantId(t); e.setGroupId(dto.groupId()); e.setFromUomId(dto.fromUomId()); e.setToUomId(dto.toUomId()); e.setFactor(dto.factor()); e.setActive(dto.active()==null?true:dto.active()); return getUomConversion(convRepo.save(e).getId());}
 @Override @Transactional public UomConversionDto updateUomConversion(UUID id,UomConversionDto dto){UUID t=tenant.requireTenantId(); var e=convRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Conversión no encontrada")); if(dto.factor()==null||dto.factor().signum()<=0) throw new BadRequestException("Factor inválido"); validateUomTenant(t,dto.groupId(),dto.fromUomId()); validateUomTenant(t,dto.groupId(),dto.toUomId()); e.setGroupId(dto.groupId()); e.setFromUomId(dto.fromUomId()); e.setToUomId(dto.toUomId()); e.setFactor(dto.factor()); if(dto.active()!=null)e.setActive(dto.active()); return getUomConversion(convRepo.save(e).getId());}
 @Override @Transactional public void deleteUomConversion(UUID id){UUID t=tenant.requireTenantId(); var e=convRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Conversión no encontrada")); softDelete(e); convRepo.save(e);} private void validateUomTenant(UUID t, UUID g, UUID u){var x=uomRepo.findByIdAndTenantIdAndDeletedAtIsNull(u,t).orElseThrow(()->new BadRequestException("UOM inválida")); if(!Objects.equals(x.getGroupId(),g)) throw new BadRequestException("UOM no pertenece al grupo");}

 @Override public PageResponse<AttributeDto> listAttributes(int page,int size,String search,Boolean active){UUID t=tenant.requireTenantId(); var p=attrRepo.findByTenantIdAndDeletedAtIsNullAndNameContainingIgnoreCaseAndActive(t,s(search),active==null?true:active,PageRequest.of(this.p(page),size)); return page(p.map(this::toAttribute),page);} private AttributeDto toAttribute(MstAttribute a){return new AttributeDto(a.getId(),a.getCode(),a.getName(),a.getType(),a.getRequired(),a.getSearchable(),a.getVisible(),a.getApplyTo(),a.getActive());}
 @Override public AttributeDto getAttribute(UUID id){UUID t=tenant.requireTenantId(); return toAttribute(attrRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Atributo no encontrado")));}
 @Override @Transactional public AttributeDto saveAttribute(AttributeDto dto){UUID t=tenant.requireTenantId(); if(attrRepo.existsByTenantIdAndCodeIgnoreCaseAndDeletedAtIsNullAndActiveTrue(t,dto.code())) throw new ConflictException("Código de atributo ya existe"); MstAttribute e=new MstAttribute(); setAttribute(e,dto,t); return getAttribute(attrRepo.save(e).getId());}
 @Override @Transactional public AttributeDto updateAttribute(UUID id,AttributeDto dto){UUID t=tenant.requireTenantId(); if(attrRepo.existsByTenantIdAndCodeIgnoreCaseAndDeletedAtIsNullAndActiveTrueAndIdNot(t,dto.code(),id)) throw new ConflictException("Código de atributo ya existe"); var e=attrRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Atributo no encontrado")); setAttribute(e,dto,t); return getAttribute(attrRepo.save(e).getId());}
 private void setAttribute(MstAttribute e, AttributeDto dto, UUID t){e.setTenantId(t); e.setCode(dto.code()); e.setName(dto.name()); e.setType(dto.type()); e.setRequired(dto.required()==null?false:dto.required()); e.setSearchable(dto.searchable()==null?false:dto.searchable()); e.setVisible(dto.visible()==null?true:dto.visible()); e.setApplyTo(dto.applyTo()==null?com.ferrisys.common.enums.catalog.ApplyToType.PRODUCT:dto.applyTo()); e.setActive(dto.active()==null?true:dto.active());}
 @Override @Transactional public void deleteAttribute(UUID id){UUID t=tenant.requireTenantId(); var e=attrRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Atributo no encontrado")); softDelete(e); attrRepo.save(e);} 
 @Override public List<AttributeOptionDto> getAttributeOptions(UUID id){UUID t=tenant.requireTenantId(); attrRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Atributo no encontrado")); return attrOptRepo.findByTenantIdAndAttributeIdAndDeletedAtIsNullAndActiveTrueOrderBySortOrderAsc(t,id).stream().map(o->new AttributeOptionDto(o.getId(),o.getValue(),o.getSortOrder(),o.getActive())).toList();}
 @Override @Transactional public List<AttributeOptionDto> replaceAttributeOptions(UUID attributeId,List<AttributeOptionDto> options){UUID t=tenant.requireTenantId(); attrRepo.findByIdAndTenantIdAndDeletedAtIsNull(attributeId,t).orElseThrow(()->new NotFoundException("Atributo no encontrado")); for(var o:attrOptRepo.findByTenantIdAndAttributeIdAndDeletedAtIsNull(t,attributeId)){softDelete(o);attrOptRepo.save(o);} for(var d:options){MstAttributeOption o=new MstAttributeOption();o.setTenantId(t);o.setAttributeId(attributeId);o.setValue(d.value());o.setSortOrder(d.sortOrder()==null?0:d.sortOrder());o.setActive(d.active()==null?true:d.active());attrOptRepo.save(o);} return getAttributeOptions(attributeId);} 

 @Override public PageResponse<TaxProfileDto> listTaxProfiles(int page,int size,String search,Boolean active){UUID t=tenant.requireTenantId(); var p=taxProfileRepo.findByTenantIdAndDeletedAtIsNullAndNameContainingIgnoreCaseAndActive(t,s(search),active==null?true:active,PageRequest.of(this.p(page),size)); return page(p.map(x->new TaxProfileDto(x.getId(),x.getName(),x.getDescription(),x.getActive())),page);} 
 @Override public TaxProfileDto getTaxProfile(UUID id){UUID t=tenant.requireTenantId(); var x=taxProfileRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Perfil tributario no encontrado")); return new TaxProfileDto(x.getId(),x.getName(),x.getDescription(),x.getActive());}
 @Override @Transactional public TaxProfileDto saveTaxProfile(TaxProfileDto dto){UUID t=tenant.requireTenantId(); if(taxProfileRepo.existsByTenantIdAndNameIgnoreCaseAndDeletedAtIsNullAndActiveTrue(t,dto.name())) throw new ConflictException("Perfil tributario ya existe"); MstTaxProfile e=new MstTaxProfile();e.setTenantId(t);e.setName(dto.name());e.setDescription(dto.description());e.setActive(dto.active()==null?true:dto.active()); try{return getTaxProfile(taxProfileRepo.save(e).getId());}catch(DataIntegrityViolationException ex){throw new ConflictException("Perfil tributario ya existe");}}
 @Override @Transactional public TaxProfileDto updateTaxProfile(UUID id,TaxProfileDto dto){UUID t=tenant.requireTenantId(); if(taxProfileRepo.existsByTenantIdAndNameIgnoreCaseAndDeletedAtIsNullAndActiveTrueAndIdNot(t,dto.name(),id)) throw new ConflictException("Perfil tributario ya existe"); var e=taxProfileRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Perfil tributario no encontrado")); e.setName(dto.name());e.setDescription(dto.description());if(dto.active()!=null)e.setActive(dto.active()); return getTaxProfile(taxProfileRepo.save(e).getId());}
 @Override @Transactional public void deleteTaxProfile(UUID id){UUID t=tenant.requireTenantId(); var e=taxProfileRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Perfil tributario no encontrado")); softDelete(e); taxProfileRepo.save(e);} 
 @Override public List<TaxProfileTaxDto> getTaxProfileTaxes(UUID id){UUID t=tenant.requireTenantId(); taxProfileRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Perfil tributario no encontrado")); return taxProfileTaxRepo.findByTenantIdAndTaxProfileIdAndDeletedAtIsNullOrderBySortOrderAsc(t,id).stream().map(x->new TaxProfileTaxDto(x.getTaxId(),x.getSortOrder(),x.getInclusive())).toList();}
 @Override @Transactional public List<TaxProfileTaxDto> replaceTaxProfileTaxes(UUID id,List<TaxProfileTaxDto> taxes){UUID t=tenant.requireTenantId(); taxProfileRepo.findByIdAndTenantIdAndDeletedAtIsNull(id,t).orElseThrow(()->new NotFoundException("Perfil tributario no encontrado")); for(var x:taxProfileTaxRepo.findByTenantIdAndTaxProfileIdAndDeletedAtIsNullOrderBySortOrderAsc(t,id)){softDelete(x);taxProfileTaxRepo.save(x);} taxes.forEach(d->{taxRepository.findByIdAndTenantIdAndActiveTrueAndDeletedAtIsNull(d.taxId(),t).orElseThrow(()->new BadRequestException("Impuesto inválido")); MstTaxProfileTax x=new MstTaxProfileTax();x.setTenantId(t);x.setTaxProfileId(id);x.setTaxId(d.taxId());x.setSortOrder(d.sortOrder()==null?0:d.sortOrder());x.setInclusive(d.inclusive()==null?false:d.inclusive()); taxProfileTaxRepo.save(x);}); return getTaxProfileTaxes(id);} 
}
